Repository adobecom/express-milo, pull requests merged in 2025-05, with the labels that each got.

#321 [MWPW-171686] App Ratings Block URL Customization
  express/code/blocks/app-ratings/app-ratings.js
  test/blocks/app-ratings/app-ratings.test.js
Labels: Ready for Review, QA Approved

#310 Authoring Enhancement Columns Block Header Size
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/ax-columns/ax-columns.js
Labels: Ready for Stage, QA Approved

#320 Stage to Main
  express/code/blocks/app-ratings/app-ratings.js
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/ax-columns/ax-columns.js
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.css
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
  express/code/blocks/pricing-cards/pricing-cards.js
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
  express/code/scripts/utils.js
  express/code/scripts/utils/pricing.js
  express/code/scripts/utils/template-ckg.js
  test/blocks/app-ratings/app-ratings.test.js
  test/scripts/pricing.test.js
  test/scripts/utils.test.js
  tools/sidekick/config.json
Labels: QA Approved

#324 [MWPW-172614] Extra Spacing In Gen AI Homepage Cards
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
Labels: Ready for Review, Ready for Stage, QA Approved

#326 Stage to Main
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
Labels: QA Approved

#328 [MWPW-172777] Fix For Pricing Table Collapse
  express/code/blocks/pricing-table/pricing-table.css
  test/blocks/pricing-table/mocks/body.html
  test/blocks/pricing-table/mocks/single-section.html
  test/blocks/pricing-table/pricing-table.test.js
Labels: Ready for Stage, QA Approved

#327 MWPW-169102-169103-169104: set approximate width and height to avoid trash layout
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
Labels: Ready for Stage, QA Approved

#325 [Q2 FY25] | UK LP Update Block for Tablet
  express/code/blocks/ax-columns/ax-columns.css
Labels: Ready for Stage, QA Approved

#319 [MWMW-169111] New Tab System
  express/code/blocks/content-toggle-v2/content-toggle-v2.css
  express/code/blocks/content-toggle-v2/content-toggle-v2.js
  test/blocks/content-toggle-v2/content-toggle-v2.test.js
  test/blocks/content-toggle-v2/mocks/body.html
Labels: Ready for Stage, QA Approved

#311 Ensure Surface Specific Table of Contents Appears Without Refresh On Correct Surface
  express/code/features/table-of-contents-seo/table-of-contents-seo.css
  express/code/features/table-of-contents-seo/table-of-contents-seo.js
  express/code/styles/styles.css
Labels: Ready for Review, QA Approved

#329 Stage to Main
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/content-toggle-v2/content-toggle-v2.css
  express/code/blocks/content-toggle-v2/content-toggle-v2.js
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
  express/code/blocks/pricing-table/pricing-table.css
  express/code/features/table-of-contents-seo/table-of-contents-seo.css
  express/code/features/table-of-contents-seo/table-of-contents-seo.js
  express/code/styles/styles.css
  test/blocks/content-toggle-v2/content-toggle-v2.test.js
  test/blocks/content-toggle-v2/mocks/body.html
  test/blocks/pricing-table/mocks/body.html
  test/blocks/pricing-table/mocks/single-section.html
  test/blocks/pricing-table/pricing-table.test.js
Labels: QA Approved

#340 Stage to Main
  express/code/blocks/ax-columns/ax-columns.css
Labels: QA Approved

#331 [MWPW-172546] Template-X QA
  express/code/blocks/template-x/template-rendering.js
  express/code/blocks/template-x/template-x.css
  express/code/blocks/template-x/template-x.js
  express/code/styles/styles.css
Labels: QA Approved, Ready for QA

#332 MWPW-171946: add focus back to cta and discover-cards
  express/code/blocks/cta-carousel/cta-carousel.css
  express/code/blocks/discover-cards/discover-cards.js
Labels: QA Approved, Ready for QA, accessibility

#330 MWPW-172779: add aria-label for check/cross icon from placeholders
  express/code/blocks/pricing-table/pricing-table.js
Labels: Ready for QA, accessibility

#333 Mobile fork null column
  express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.css
  express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.js
  express/code/blocks/mobile-fork-button/mobile-fork-button.css
  express/code/blocks/mobile-fork-button/mobile-fork-button.js
  test/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.test.js
  test/blocks/mobile-fork-button-frictionless/mocks/body.html
  test/blocks/mobile-fork-button/mobile-fork-button.test.js
  test/blocks/mobile-fork-button/mocks/body.html
Labels: QA Approved

#347 Stage to Main
  express/code/blocks/cta-carousel/cta-carousel.css
  express/code/blocks/discover-cards/discover-cards.js
  express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.css
  express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.js
  express/code/blocks/mobile-fork-button/mobile-fork-button.css
  express/code/blocks/mobile-fork-button/mobile-fork-button.js
  express/code/blocks/pricing-table/pricing-table.js
  express/code/blocks/template-x/template-rendering.js
  express/code/blocks/template-x/template-x.css
  express/code/blocks/template-x/template-x.js
  express/code/styles/styles.css
  test/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.test.js
  test/blocks/mobile-fork-button-frictionless/mocks/body.html
  test/blocks/mobile-fork-button/mobile-fork-button.test.js
  test/blocks/mobile-fork-button/mocks/body.html
Labels: Ready for QA

#358 Turn off Browse API Calls on Template Search Pages
  express/code/scripts/utils/browse-api-controller.js
Labels: QA Approved, Ready for QA, attention needed

#355 [MWPW-173736] Fix undefined templates params
  express/code/blocks/template-x/template-rendering.js
Labels: QA Approved, Ready for QA

#354 [MWPW-173484] View All Button Aria
  express/code/blocks/cta-carousel/cta-carousel.js
Labels: QA Approved, Ready for QA, accessibility

#351 [MWPW-172781] Fullscreen Marquee Free Plan Widget Update
  express/code/blocks/fullscreen-marquee/fullscreen-marquee.css
Labels: QA Approved, Ready for QA, accessibility

#350 [MWPW-173637] - Shrink Assets Too Large
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.css
Labels: QA Approved, Ready for QA, attention needed

#345 Semantic quote block
  express/code/blocks/quotes/quotes.css
  express/code/blocks/quotes/quotes.js
Labels: QA Approved, Ready for QA, accessibility

#343 MWPW-172189: enlarges icon share template X
  express/code/blocks/holiday-blade/holiday-blade.css
  express/code/blocks/template-x/template-x.css
Labels: QA Approved, Ready for QA, accessibility

#338 MWPW-171884-MWPW-173622: change invalid aria-role to role
  express/code/blocks/how-to-steps-carousel/how-to-steps-carousel.js
Labels: QA Approved, Ready for QA, accessibility

#342 [MWPW-171954][Sev-1] Frictionless QA 320px Legal Text
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
Labels: QA Approved, accessibility, attention needed

#362 MWPW-173643: remove unnecessary aria labels
  express/code/blocks/discover-cards/discover-cards.js
Labels: QA Approved, accessibility

#363 [MWPW-172674][Sev-1] Remove Colorful Heading Text
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
Labels: QA Approved, accessibility, attention needed

#346 MWPW-172512: add discerning text to link aria-label
  express/code/blocks/template-x/template-rendering.js
Labels: Ready for QA, accessibility, attention needed

#373 [MWPW-173635] Stronger Contrast Text For Pricing Table
  express/code/blocks/pricing-table/pricing-table.css
Labels: Ready for QA, accessibility, attention needed
