Repository adobecom/express-milo, pull requests merged in 2025-07, with the labels that each got.

#452 Wayfinder background
  express/code/blocks/wayfinder/README.md
  express/code/blocks/wayfinder/wayfinder.css
  express/code/blocks/wayfinder/wayfinder.js
Labels: Ready for Stage, QA Approved

#465 [Release] Stage -> Main
  express/code/blocks/wayfinder/README.md
  express/code/blocks/wayfinder/wayfinder.css
  express/code/blocks/wayfinder/wayfinder.js
Labels: QA Approved

#442 [MWPW-170573] Leaky Regex Fix
  express/code/scripts/utils/template-ckg.js
Labels: Ready for Stage, QA Approved

#457 MWPW-173964 - AEXG5198 | RTP | (mWeb) Homepage
  express/code/blocks/mobile-fork-button-dismissable/mobile-fork-button-dismissable.css
  express/code/blocks/mobile-fork-button-dismissable/mobile-fork-button-dismissable.js
  express/code/scripts/utils.js
  test/blocks/mobile-fork-button-dismissable/mobile-fork-button-dismissable.test.js
  test/blocks/mobile-fork-button-dismissable/mocks/body.html
Labels: Ready for Stage, QA Approved

#474 [Chore] UTC -> PST
  .github/workflows/helpers.js
Labels: QA Approved

#460 Multiple Header Support For Browse By Category
  express/code/blocks/browse-by-category/browse-by-category.js
Labels: Ready for Stage, QA Approved, accessibility

#475 [MWPW-176361] Filter Invalid Templates for Template-x-carousel-toolbar
  express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.js
  express/code/scripts/template-utils.js
Labels: Ready for Stage, QA Approved

#489 Fix certain blog templates not rendering
  express/code/templates/blog/blog.js
Labels: Ready for Stage

#488 Floating button
  nala/blocks/floating-button/floating-button.page.cjs
  nala/blocks/floating-button/floating-button.spec.cjs
  nala/blocks/floating-button/floating-button.test.cjs
Labels: QA Approved, zero-impact, run-nala, @floating-button

#494 Pricing Card CSS Fix
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
Labels: QA Approved, attention needed

#450 Browse by category carousel fix
  express/code/scripts/widgets/carousel.js
Labels: QA Approved

#495 [MWPW-175453][MWPW-175454] TaaS Topics AND support + Backup Recipe support
  .eslintrc.cjs
  .gitignore
  express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.js
  express/code/blocks/templates-as-a-service/README.md
  express/code/blocks/templates-as-a-service/build-lit.zsh
  express/code/blocks/templates-as-a-service/library/.gitignore
  express/code/blocks/templates-as-a-service/library/dist/templates-as-a-service.css
  express/code/blocks/templates-as-a-service/library/dist/templates-as-a-service.min.es.js
  express/code/blocks/templates-as-a-service/library/dist/templates-as-a-service.min.es.js.map
  express/code/blocks/templates-as-a-service/library/dist/vite.svg
  express/code/blocks/templates-as-a-service/library/eslint.config.js
  express/code/blocks/templates-as-a-service/library/index.html
  express/code/blocks/templates-as-a-service/library/package-lock.json
  express/code/blocks/templates-as-a-service/library/package.json
  express/code/blocks/templates-as-a-service/library/public/vite.svg
  express/code/blocks/templates-as-a-service/library/src/App.css
  express/code/blocks/templates-as-a-service/library/src/App.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/Form.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/Label.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/fields/InfoButton.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/fields/NumberField.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/fields/SelectField.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/fields/TextArea.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/fields/TextField.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/topics/TopicsGroups.jsx
  express/code/blocks/templates-as-a-service/library/src/components/index.js
  express/code/blocks/templates-as-a-service/library/src/components/providers/ErrorBoundary.jsx
  express/code/blocks/templates-as-a-service/library/src/components/providers/FormInfoProvider.jsx
  express/code/blocks/templates-as-a-service/library/src/components/providers/FormProvider.jsx
  express/code/blocks/templates-as-a-service/library/src/components/providers/index.js
  express/code/blocks/templates-as-a-service/library/src/components/recipe/Recipe.jsx
  express/code/blocks/templates-as-a-service/library/src/components/results/QueryResults.jsx
  express/code/blocks/templates-as-a-service/library/src/components/results/Template.jsx
  express/code/blocks/templates-as-a-service/library/src/components/support/Support.jsx
  express/code/blocks/templates-as-a-service/library/src/dev-styles.css
  express/code/blocks/templates-as-a-service/library/src/main.jsx
  express/code/blocks/templates-as-a-service/library/src/utils/form-hooks.js
  express/code/blocks/templates-as-a-service/library/src/utils/recipe-form-utils.js
  express/code/blocks/templates-as-a-service/library/vite.config.js
  express/code/blocks/templates-as-a-service/lit.js
  express/code/blocks/templates-as-a-service/lit.min.js
  express/code/blocks/templates-as-a-service/recipe-editor.js
  express/code/blocks/templates-as-a-service/taas-results.js
  express/code/blocks/templates-as-a-service/templates-as-a-service.css
  express/code/blocks/templates-as-a-service/templates-as-a-service.js
  express/code/scripts/template-utils.js
  package-lock.json
  package.json
  test/scripts/template-utils.test.js
Labels: Ready for Stage, zero-impact

#466 [Bug] Page Margin Break on Content Block (Trim Video Page)
  express/code/styles/styles.css
Labels: Ready for Stage, QA Approved

#509 [MWPW-176181] SUSI-Light Student
  express/code/blocks/susi-light/susi-light.css
  express/code/blocks/susi-light/susi-light.js
Labels: Ready for Stage, QA Approved
