Repository adobecom/express-milo, pull requests merged in 2025-02, with the labels that each got.

#135 Adding accessibility attributes to share button
  express/code/blocks/template-x/template-rendering.js
Labels: Ready for Stage

#165 MWPW-164896 - Fix toggle bar to be semantic markup
  express/code/blocks/toggle-bar/toggle-bar.css
  express/code/blocks/toggle-bar/toggle-bar.js
Labels: Ready for Review, Ready for Stage

#164 MWPW-164904 - Wayfinder buttons not associated with text
  express/code/blocks/wayfinder/wayfinder.js
Labels: Ready for Review, Ready for Stage

#160 MWPW-164899 - Adjust color for copy to clipboard tooltip
  express/code/blocks/template-x/template-x.css
  express/code/styles/styles.css
Labels: Ready for Review, Ready for Stage

#159 MWPW-164908 - Play pause label accessibility update
  express/code/blocks/ax-marquee/ax-marquee.css
  express/code/blocks/ax-marquee/ax-marquee.js
Labels: Ready for Review, Ready for Stage

#158 MWPW-165757 - Fix cards text getting cutt off at widths below 360px.
  express/code/blocks/pricing-cards/pricing-cards.css
Labels: Ready for Review, Ready for Stage

#157 Template List Updates To Align With Discover Page Redesign
  express/code/blocks/template-list/template-list.js
  express/code/scripts/widgets/basic-carousel.css
  express/code/scripts/widgets/basic-carousel.js
Labels: Ready for Review, Ready for Stage

#172 Allow Background Image in AX-Columns Block
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/ax-columns/ax-columns.js
Labels: Ready for Review

#154 Create Highlight Blade
  express/code/blocks/highlight/highlight.css
  express/code/blocks/highlight/highlight.js
Labels: Ready for Review

#162 Secondary Button Contrast Ratio
  express/code/styles/styles.css
Labels: Ready for Stage

#128 Port HowToV2 block from express to milo
  express/code/blocks/how-to-v2/how-to-v2.css
  express/code/blocks/how-to-v2/how-to-v2.js
  test/blocks/how-to-v2/how-to-v2.test.js
  test/blocks/how-to-v2/mocks/body.html
Labels: Ready for Review

#155 FaqV2 Updates
  express/code/blocks/faqv2/faqv2.css
  express/code/blocks/faqv2/faqv2.js
Labels: Ready for Review

#174 Promotions Block Changes for JP LongForm Milo
  express/code/blocks/promotion/promotion.css
Labels: Ready for Review

#178 Print PDP
  express/code/blocks/link-list/link-list.css
  express/code/blocks/template-x/template-rendering.js
  express/code/blocks/template-x/template-x.css
  express/code/blocks/template-x/template-x.js
  express/code/blocks/template-x/tshirt.png
  express/code/styles/styles.css
Labels: Ready for Review

#166 Sync Stage with Main
  express/code/blocks/ax-marquee/ax-marquee.css
  express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.css
  express/code/blocks/mobile-fork-button/mobile-fork-button.css
Labels: Ready for Review

#184 Ensure Blog Page Content Aligns With Figma
  express/code/styles/styles.css
Labels: Ready for Review, Ready for Stage

#177 MWPW-164903 - Play/pause tooltip included in hover hit area
  express/code/blocks/ax-marquee/ax-marquee.css
Labels: Ready for Stage

#175 Fullscreen Marquee Block Changes for JP LongForm Milo
  express/code/blocks/fullscreen-marquee/fullscreen-marquee.css
Labels: Ready for Review, Ready for Stage

#173 Teams vs Enterprise Blade
  express/code/blocks/content-cards/content-cards.css
  express/code/blocks/content-cards/content-cards.js
Labels: Ready for Review, Ready for Stage

#171 CTA Carousel Cards Update
  express/code/blocks/cta-carousel/cta-carousel.js
Labels: Ready for Review, Ready for Stage

#167 Aria live template copy
  express/code/blocks/template-x/template-rendering.js
  express/code/blocks/template-x/template-x.css
Labels: Ready for Stage

#190 Create Highlight Blade 2
  express/code/blocks/highlight/highlight.css
  express/code/blocks/highlight/highlight.js
Labels: Ready for Stage

#192 Promotions Block Changes for JP LongForm Milo 2
  express/code/blocks/promotion/promotion.css
Labels: Ready for Stage

#193 Ensure JP Content Is Padded On Mobile Devices On Left And Right
  express/code/styles/styles.css
Labels: Ready for Stage

#187 Fix For Pricing Table Wrapper
  express/code/blocks/pricing-table/pricing-table.css
  express/code/blocks/pricing-table/pricing-table.js
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
Labels: Ready for Review

#195 Ensure Default Content Width Aligns With Figma Across Devices
  express/code/styles/styles.css
Labels: Ready for Review

#211 Link blade
  express/code/blocks/link-blade/link-blade.css
  express/code/blocks/link-blade/link-blade.js
  test/blocks/link-blade/link-blade.test.js
  test/blocks/link-blade/mocks/body.html
Labels: Ready for Stage

#209 [DOTCOM-139510] FloatingCTA Error Handling for Invalid Target Links
  express/code/scripts/utils.js
Labels: Ready for Stage

#207 MWPW-164894 Heading Tag Type Change
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.js
Labels: Ready for Stage

#206 [MWPW-168298] Update SUSI Signin Detection
  express/code/blocks/susi-light/susi-light.js
Labels: Ready for Stage

#200 MWPW-168115 - Add keyboard navigation to work with play/pause tooltip
  express/code/blocks/ax-marquee/ax-marquee.css
  express/code/blocks/ax-marquee/ax-marquee.js
Labels: Ready for Stage

#204 [MWPW-167968] Remove Android RAM check from checking Frictionless eligibility
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
  express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.js
  express/code/blocks/mobile-fork-button/mobile-fork-button.js
Labels: Ready for Stage

#205 Restore Configurable Show Content Functionality Of The Pricing Table
  express/code/blocks/pricing-table/pricing-table.js
Labels: Ready for Stage

#188 Teams vs Enterprise Blade - Add Black Border to CTA
  express/code/blocks/content-cards/content-cards.css
Labels: Ready for Stage

#217 Business Hub - dWeb / mWeb - Text Block CTA Alignment
  express/code/styles/styles.css
Labels: Ready for Stage

#227 Business Hub - Consolidated Branch
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/banner/banner.css
  express/code/blocks/content-toggle/content-toggle.css
  express/code/blocks/content-toggle/content-toggle.js
  express/code/blocks/discover-cards/discover-cards.css
  express/code/blocks/headline/headline.css
  express/code/blocks/headline/headline.js
  express/code/blocks/logo-row/logo-row.css
  express/code/blocks/pricing-table/pricing-table.css
  express/code/blocks/pricing-table/pricing-table.js
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
  express/code/styles/styles.css
Labels: Ready for Stage

#208 Business Hub - mWeb / Desktop - Logo Wall
  express/code/blocks/logo-row/logo-row.css
Labels: Ready for Review

#215 Business Hub - mWeb / Desktop - Success KPIs
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/pricing-table/pricing-table.js
Labels: Ready for Review

#220 Business Hub - mWeb - Banner Blade
  express/code/blocks/banner/banner.css
Labels: Ready for Review

#228 [MWPW-168746] Enable summit bacom dynamic nav
  express/code/scripts/scripts.js
Labels: Ready for Stage
