Repository adobecom/express-milo, pull requests merged in 2025-09, with the labels that each got.

#580 adjusted max-width of the frictionless quick action button container …
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
Labels: QA Approved

#584 [MWPW-155657][Test] Template-x tworow experiment
  express/code/blocks/template-x/template-x.css
  express/code/blocks/template-x/template-x.js
Labels: QA Approved

#587 adjusted CSS of discovery-cards flip variant
  express/code/blocks/discover-cards/discover-cards.css
Labels: QA Approved

#563 Pricing Cards Fast Follow
  express/code/blocks/pricing-cards-v2/README.md
  express/code/blocks/pricing-cards-v2/pricing-cards-v2.css
  express/code/blocks/pricing-cards-v2/pricing-cards-v2.js
  express/code/blocks/simplified-pricing-cards-v2/README.md
  express/code/blocks/simplified-pricing-cards-v2/simplified-pricing-cards-v2.css
  express/code/blocks/simplified-pricing-cards-v2/simplified-pricing-cards-v2.js
  express/code/scripts/widgets/image-tooltip.js
  express/code/scripts/widgets/tooltip.js
  express/code/styles/styles.css
  test/blocks/pricing-cards-v2/mocks/body.html
  test/blocks/pricing-cards-v2/pricing-cards-v2.test.js
  test/blocks/simplified-pricing-cards-v2/mocks/body.html
  test/blocks/simplified-pricing-cards-v2/simplified-pricing-cards-v2.test.js
Labels: QA Approved

#577 Discover - TOC Small Bugs (Hover desktop, tablet scroll sticky)
  express/code/blocks/toc-seo/toc-seo.css
  express/code/blocks/toc-seo/toc-seo.js
Labels: QA Approved

#582 JP: Q3 - Discover Page Optimization
  express/code/styles/styles.css
Labels: Ready for Review, QA Approved

#559 [CCEX-203130][MWPW-179566] - Frictionless upload for feature pages | Creation of UploadService in express-milo
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
  express/code/scripts/scripts.js
  express/code/scripts/upload-service/.gitignore
  express/code/scripts/upload-service/README.md
  express/code/scripts/upload-service/dist/EnhancedLogging-ycbPCFZ4.min.js
  express/code/scripts/upload-service/dist/EnhancedLogging-ycbPCFZ4.min.js.map
  express/code/scripts/upload-service/dist/Logging-CoIJWvXW.min.js
  express/code/scripts/upload-service/dist/index-Dj6VB_pE.min.js
  express/code/scripts/upload-service/dist/upload-service.min.es.js
  express/code/scripts/upload-service/dist/upload-service.min.es.js.map
  express/code/scripts/upload-service/eslint.config.js
  express/code/scripts/upload-service/package-lock.json
  express/code/scripts/upload-service/package.json
  express/code/scripts/upload-service/src/consts.ts
  express/code/scripts/upload-service/src/events.ts
  express/code/scripts/upload-service/src/globals.d.ts
  express/code/scripts/upload-service/src/index.ts
  express/code/scripts/upload-service/src/types.ts
  express/code/scripts/upload-service/src/upload-service/EnhancedLogging.ts
  express/code/scripts/upload-service/src/upload-service/Logging.ts
  express/code/scripts/upload-service/src/upload-service/UploadService.ts
  express/code/scripts/upload-service/src/upload-service/index.ts
  express/code/scripts/upload-service/tsconfig.json
  express/code/scripts/upload-service/vite.config.js
  express/code/scripts/utils/assetDecoder.js
  express/code/scripts/utils/createProgressBar.js
  express/code/scripts/utils/frictionless-utils.js
Labels: QA Approved

#527 DEV ENHANCEMENT: Pre-commit Hook For Linting CSS Vars Updates
  scripts/lint-css-vars.js
  scripts/lint-css-vars.md
Labels: Ready for Stage, zero-impact

#622 update how-to-steps-carousel and icon-list block.
  nala/blocks/how-to-steps-carousel/how-to-steps-carousel.spec.cjs
  nala/blocks/how-to-steps-carousel/how-to-steps-carousel.test.cjs
  nala/blocks/icon-list/icon-list.page.cjs
  nala/blocks/icon-list/icon-list.spec.cjs
  nala/blocks/icon-list/icon-list.test.cjs
Labels: Ready for Stage, zero-impact, run-nala

#615 MWPW-179214: Fix template-x-promo Nala test paths > /drafts/nala/blocks/ pattern
  nala/blocks/template-x-promo/template-x-promo.page.cjs
  nala/blocks/template-x-promo/template-x-promo.spec.cjs
  nala/blocks/template-x-promo/template-x-promo.test.cjs
Labels: Ready for Stage, zero-impact, run-nala

#623 MWPW-180211: add date to blog post v2
  express/code/blocks/blog-posts-v2/blog-posts-v2.css
  express/code/blocks/blog-posts-v2/blog-posts-v2.js
  express/code/scripts/utils/ratings-utils.js
  test/blocks/blog-posts-v2/blog-posts-v2.test.js
  test/blocks/blog-posts-v2/mocks/body.html
Labels: QA Approved, run-nala

#633 MWPW-179757: Fix mobile z-index issue in drawer-cards and grid-marquee blocks
  express/code/blocks/drawer-cards/drawer-cards.css
  express/code/blocks/grid-marquee/grid-marquee.css
  nala/blocks/grid-marquee/grid-marquee.spec.cjs
  nala/blocks/grid-marquee/grid-marquee.test.cjs
  test/blocks/drawer-cards/drawer-cards.test.js
  test/blocks/drawer-cards/mocks/body.html
  test/blocks/grid-marquee/grid-marquee.test.js
  test/blocks/grid-marquee/mocks/body.html
Labels: Ready for Review, run-nala

#636 Stage to Main
  .github/workflows/codeql.yml
  .github/workflows/pr-reminder-daily.yml
  .github/workflows/qa-label-management.yml
  .github/workflows/run-nala-default.yml
  .github/workflows/slack-release-notification.yml
  .github/workflows/test-workflows.yml
  .gitignore
  .yamllint
  DAILY-PR-REMINDER-DOCUMENTATION.md
  QA-LABEL-MANAGEMENT-DOCUMENTATION.md
  RELEASE-NOTIFICATION-DOCUMENTATION.md
  express/code/blocks/drawer-cards/drawer-cards.css
  express/code/blocks/grid-marquee/grid-marquee.css
  express/code/blocks/toc-seo/toc-seo.css
  express/code/blocks/toc-seo/toc-seo.js
  nala/blocks/grid-marquee/grid-marquee.spec.cjs
  nala/blocks/grid-marquee/grid-marquee.test.cjs
  nala/utils/pr.run.sh
  scripts/simple-workflow-test.js
  scripts/tests/qa-label-management.test.js
  test/blocks/drawer-cards/drawer-cards.test.js
  test/blocks/drawer-cards/mocks/body.html
  test/blocks/grid-marquee/grid-marquee.test.js
  test/blocks/grid-marquee/mocks/body.html
Labels: Ready for Review, QA Approved

#640 Frictionless QA video upload automated tests
  nala/assets/test-video.mp4
  nala/blocks/frictionless-qa-video/frictionless-qa-video.page.cjs
  nala/blocks/frictionless-qa-video/frictionless-qa-video.spec.cjs
  nala/blocks/frictionless-qa-video/frictionless-qa-video.test.cjs
Labels: Ready for Review, zero-impact

#646 added ax-ai-assistant.svg icon into /icons directory
  express/code/icons/ax-ai-assistant.svg
Labels: QA Approved

#655 Add drafts folders for dev testing
  fstab.yaml
Labels: Ready for Stage, zero-impact
