Repository adobecom/express-milo, pull requests merged in 2025-03, with the labels that each got.

#231 Print qa fixes
  express/code/blocks/template-x/template-rendering.js
  express/code/blocks/template-x/template-x.css
Labels: Ready for Stage

#212 MWPW-164913 - Edit this template button accessibility update
  express/code/blocks/template-x/template-rendering.js
Labels: Ready for Stage

#232 Link Blade Text Decoration Fix
  express/code/blocks/link-blade/link-blade.css
Labels: Ready for Stage

#214 Stage to Main Releases
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/ax-marquee/ax-marquee.css
  express/code/blocks/ax-marquee/ax-marquee.js
  express/code/blocks/banner/banner.css
  express/code/blocks/content-cards/content-cards.css
  express/code/blocks/content-toggle/content-toggle.css
  express/code/blocks/content-toggle/content-toggle.js
  express/code/blocks/discover-cards/discover-cards.css
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.js
  express/code/blocks/headline/headline.css
  express/code/blocks/headline/headline.js
  express/code/blocks/link-blade/link-blade.css
  express/code/blocks/link-blade/link-blade.js
  express/code/blocks/logo-row/logo-row.css
  express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.js
  express/code/blocks/mobile-fork-button/mobile-fork-button.js
  express/code/blocks/pricing-table/pricing-table.css
  express/code/blocks/pricing-table/pricing-table.js
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
  express/code/blocks/susi-light/susi-light.js
  express/code/blocks/template-x/template-rendering.js
  express/code/blocks/template-x/template-x.css
  express/code/scripts/branchlinks.js
  express/code/scripts/scripts.js
  express/code/scripts/utils.js
  express/code/styles/styles.css
  test/blocks/link-blade/link-blade.test.js
  test/blocks/link-blade/mocks/body.html
Labels: QA Approved

#234 [MWPW-169176] Fix Issue of floatingCTA Not Getting Suppressed after Mobile Frictionless Uploads
  express/code/scripts/widgets/floating-cta.css
Labels: Ready for Stage

#229 [MWPW-168740] Duplicate grid-marquee icons and add ax- prefix
  express/code/icons/ax-add-on.svg
  express/code/icons/ax-ai.svg
  express/code/icons/ax-asset.svg
  express/code/icons/ax-caption.svg
  express/code/icons/ax-convert.svg
  express/code/icons/ax-crop.svg
  express/code/icons/ax-explore-photo.svg
  express/code/icons/ax-explore-templates.svg
  express/code/icons/ax-explore-video.svg
  express/code/icons/ax-generate-image.svg
  express/code/icons/ax-generative-fill.svg
  express/code/icons/ax-merge-video.svg
  express/code/icons/ax-microphone.svg
  express/code/icons/ax-music.svg
  express/code/icons/ax-remove-background.svg
  express/code/icons/ax-resize.svg
  express/code/icons/ax-start-from-templates.svg
  express/code/icons/ax-text-to-speech.svg
  express/code/icons/ax-trim-video.svg
  express/code/icons/ax-upload.svg
Labels: Ready for Stage

#194 Center Highlight Blade On Mobile
  express/code/blocks/highlight/highlight.css
Labels: Ready for Review

#196 PR To Ensure FAQV2 / FAQV2-Bold Variant Aligns Widths Across Devices
  express/code/blocks/faqv2/faqv2.css
Labels: Ready for Review

#213 [MWPW-168469] Stage domains map
  express/code/scripts/scripts.js
Labels: Ready for Review

#216 MWPW-167196: Added additional icons
  express/code/icons/AX_AIGenerate_18_N.svg
  express/code/icons/AX_AIGenerate_18_S.svg
  express/code/icons/AX_AIRecolor_18_N.svg
  express/code/icons/AX_AIRecolor_18_S.svg
  express/code/icons/AX_AISparkles_18_N.svg
  express/code/icons/AX_AISparkles_18_S.svg
  express/code/icons/AX_Brand_18_N.svg
  express/code/icons/AX_Brand_18_S.svg
  express/code/icons/AX_Briefcase_18_N.svg
  express/code/icons/AX_Briefcase_18_S.svg
  express/code/icons/AX_Flyer_18_N.svg
  express/code/icons/AX_Flyer_44_S.svg
  express/code/icons/AX_Image_18_N.svg
  express/code/icons/AX_Image_18_S.svg
  express/code/icons/AX_MortarboardHat_18_N.svg
  express/code/icons/AX_MortarboardHat_18_S.svg
  express/code/icons/AX_PDFExport_18_N.svg
  express/code/icons/AX_PDFExport_18_S.svg
  express/code/icons/AX_Print_18_N.svg
  express/code/icons/AX_Print_18_S.svg
  express/code/icons/AX_QRCode_18_N.svg
  express/code/icons/AX_QRCode_18_S.svg
  express/code/icons/AX_ThumbUp_18_N.svg
  express/code/icons/AX_ThumbUp_18_S.svg
  express/code/icons/AX_Video_18_N.svg
  express/code/icons/AX_Video_18_S.svg
Labels: Ready for Stage

#237 Removed conflicting style
  express/code/styles/styles.css
Labels: Ready for Stage

#233 [ACE1057]: grid marquee toggle feature
  express/code/scripts/mep/ace1057/grid-marquee/grid-marquee.css
  express/code/scripts/mep/ace1057/grid-marquee/grid-marquee.js
Labels: Ready for Stage

#239 AEXG5198 | ENUS, UK, IN | (mWeb) Homepage Test
  express/code/scripts/mep/aexg5198/grid-marquee/grid-marquee.css
  express/code/scripts/mep/aexg5198/grid-marquee/grid-marquee.js
  express/code/scripts/mep/aexg5198/mobile-fork-button/mobile-fork-button.css
  express/code/scripts/mep/aexg5198/mobile-fork-button/mobile-fork-button.js
Labels: Ready for Stage

#236 [MWPW-167750] Full Editor For Remove Background
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
Labels: Ready for Stage

#243 Cc everywhere variant param v2
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
Labels: Ready for Stage

#244 New Login Page
  express/code/blocks/floating-panel/floating-panel.css
  express/code/blocks/floating-panel/floating-panel.js
  express/code/blocks/login-page/login-page.css
  express/code/blocks/login-page/login-page.js
  express/code/blocks/susi-light/susi-light.css
  express/code/blocks/susi-light/susi-light.js
  express/code/icons/ax-badge-dark.svg
  express/code/icons/ax-globe.svg
  express/code/icons/ax-web-dark.svg
  express/code/scripts/express-delayed.js
  test/blocks/floating-panel/floating-panel.test.js
  test/blocks/floating-panel/mocks/body.html
  test/blocks/grid-marquee/mocks/body.html
  test/blocks/login-page/login-page.test.js
  test/blocks/login-page/mocks/body.html
  test/blocks/susi-light/mocks/body.html
  test/blocks/susi-light/susi-light.test.js
Labels: Ready for Stage

#250 Add Analytics To Frictionless QA Experiment
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
  express/code/scripts/instrument.js
Labels: do not merge

#248 [Q1 FY25 | SEO] Discover More Cards
  express/code/blocks/discover-cards/discover-cards.css
  express/code/blocks/discover-cards/discover-cards.js
  express/code/icons/minus-icon.svg
  express/code/icons/plus-circle-icon.svg
Labels: Ready for Stage

#252 [MWPW-169843] Revert Added SDK Property
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
  express/code/scripts/instrument.js
Labels: Ready for Review

#256 Stage to Main
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
  express/code/scripts/instrument.js
  express/code/scripts/utils.js
Labels: QA Approved

#254 [JDI SPOT FIX] Hiding non loaded promotion
  express/code/styles/styles.css
Labels: Ready for Stage

#265 MWPW-169989: added icons
  express/code/icons/ax-SX_Threads_44_N.svg
  express/code/icons/ax-S_BeSolid_18_N.svg
  express/code/icons/ax-add-ons-22.svg
  express/code/icons/ax-caption-video-22.svg
  express/code/icons/ax-clip-maker-22.svg
  express/code/icons/ax-convert-22.svg
  express/code/icons/ax-convert-to-gif-22.svg
  express/code/icons/ax-crop-image-22.svg
  express/code/icons/ax-design-assets-22.svg
  express/code/icons/ax-generate-image-22.svg
  express/code/icons/ax-generate-similar-22.svg
  express/code/icons/ax-generate-template.svg
  express/code/icons/ax-generate-video-22.svg
  express/code/icons/ax-generate-voice-22.svg
  express/code/icons/ax-insert-remove-object-22.svg
  express/code/icons/ax-merge-video-22.svg
  express/code/icons/ax-photos-22.svg
  express/code/icons/ax-remove-bg-22.svg
  express/code/icons/ax-resize-image-22.svg
  express/code/icons/ax-resize-video-22.svg
  express/code/icons/ax-start-from-media-22.svg
  express/code/icons/ax-start-from-scratch-22.svg
  express/code/icons/ax-start-from-templates.svg
  express/code/icons/ax-templates-22.svg
  express/code/icons/ax-trim-video.svg
  express/code/icons/ax-video-22.svg
Labels: Ready for Review

#258 [MWPW-167121][Login Page] Lower floating panel
  express/code/blocks/floating-panel/floating-panel.css
  express/code/blocks/susi-light/susi-light.css
Labels: Ready for Stage

#262 [MWPW-170094] Hero Section logo Injection
  express/code/scripts/scripts.js
  express/code/styles/styles.css
Labels: Ready for Review, Ready for Stage

#199 Basic Template Grid Carousel - Version 2
  express/code/blocks/template-x/template-x.js
  express/code/scripts/utils/load-carousel.js
  express/code/scripts/widgets/basic-carousel.css
  express/code/scripts/widgets/basic-carousel.js
Labels: Ready for Review

#266 Stage to Main
  express/code/blocks/floating-panel/floating-panel.css
  express/code/blocks/grid-marquee/grid-marquee.css
  express/code/blocks/grid-marquee/grid-marquee.js
  express/code/blocks/susi-light/susi-light.css
  express/code/blocks/template-x/template-x.js
  express/code/icons/ax-SX_Threads_44_N.svg
  express/code/icons/ax-S_BeSolid_18_N.svg
  express/code/icons/ax-add-ons-22.svg
  express/code/icons/ax-caption-video-22.svg
  express/code/icons/ax-clip-maker-22.svg
  express/code/icons/ax-convert-22.svg
  express/code/icons/ax-convert-to-gif-22.svg
  express/code/icons/ax-crop-image-22.svg
  express/code/icons/ax-design-assets-22.svg
  express/code/icons/ax-generate-image-22.svg
  express/code/icons/ax-generate-similar-22.svg
  express/code/icons/ax-generate-template.svg
  express/code/icons/ax-generate-video-22.svg
  express/code/icons/ax-generate-voice-22.svg
  express/code/icons/ax-insert-remove-object-22.svg
  express/code/icons/ax-merge-video-22.svg
  express/code/icons/ax-photos-22.svg
  express/code/icons/ax-remove-bg-22.svg
  express/code/icons/ax-resize-image-22.svg
  express/code/icons/ax-resize-video-22.svg
  express/code/icons/ax-start-from-media-22.svg
  express/code/icons/ax-start-from-scratch-22.svg
  express/code/icons/ax-start-from-templates.svg
  express/code/icons/ax-templates-22.svg
  express/code/icons/ax-trim-video.svg
  express/code/icons/ax-video-22.svg
  express/code/scripts/scripts.js
  express/code/scripts/utils/load-carousel.js
  express/code/scripts/widgets/basic-carousel.css
  express/code/scripts/widgets/basic-carousel.js
  express/code/styles/styles.css
Labels: QA Approved

#269 [Eng Enhancements] Why Choose Express Page - Default Toggle Teams first
  express/code/blocks/content-toggle/content-toggle.js
Labels: Ready for Review

#270 Padding Issue For Right Toggle Button When Window Resized
  express/code/blocks/content-toggle/content-toggle.js
Labels: Ready for Review

#273 [Eng Enhancements] Why Choose Express Page - Default Toggle Teams first - 2
  express/code/blocks/content-toggle/content-toggle.js
Labels: Ready for Review

#271 Stage to main
  express/code/blocks/content-toggle/content-toggle.js
Labels: QA Approved
