Repository adobecom/express-milo, pull requests merged in 2025-06, with the labels that each got.

#348 [MWPW-172869][Sev-1] Content Toggle Low Res Fix
  express/code/blocks/content-toggle/content-toggle.css
  express/code/blocks/content-toggle/content-toggle.js
Labels: Ready for QA, accessibility, attention needed

#369 [MWPW-172612][Sev-1] Update Floating CTA Color
  express/code/scripts/widgets/floating-cta.css
  express/code/styles/styles.css
Labels: Ready for Stage, Ready for QA, accessibility, attention needed

#371 [MWPW-174225][Tech Debt] Placeholders for FQA-Mobile
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
Labels: Ready for Stage, attention needed

#381 Stage to main: RC 25-22
  express/code/blocks/ax-columns/ax-columns.js
  express/code/blocks/content-toggle/content-toggle.css
  express/code/blocks/content-toggle/content-toggle.js
  express/code/blocks/discover-cards/discover-cards.js
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
  express/code/blocks/pricing-table/pricing-table.css
  express/code/blocks/pricing-table/pricing-table.js
  express/code/blocks/template-x/template-rendering.js
  express/code/blocks/template-x/template-x.css
  express/code/scripts/utils/ax-video-controls.js
  express/code/scripts/utils/media.js
  express/code/scripts/widgets/floating-cta.css
  express/code/styles/styles.css
Labels: QA Approved, Ready for QA

#394 Update template api headers
  express/code/scripts/template-search-api-v3.js
Labels: Ready for Stage

#396 Pulling main workflow files into stage.
  .github/workflows/helpers.js
  .github/workflows/merge-to-main.js
  .github/workflows/merge-to-main.yaml
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
  package-lock.json
  package.json
Labels: zero-impact

#398 Modified helper to not rely on local .evn credentials
  .github/workflows/helpers.js
Labels: zero-impact

#399 merge to stage mod
  .github/workflows/merge-to-stage.yaml
Labels: zero-impact

#400 merge to stage mod
  .github/workflows/merge-to-stage.yaml
Labels: zero-impact

#372 [MWPW-173182][Sitemap] Added x-default hreflang
  helix-sitemap.yaml
Labels: Ready for Stage

#391 [MWPW-174592] [NALA][Express] Onboard Nala Framework for Automated Testing in Express Project
  .eslintrc.cjs
  .github/workflows/run-nala-label.yml
  .gitignore
  README.md
  nala/blocks/ax-columns/ax-columns.page.cjs
  nala/blocks/ax-columns/ax-columns.spec.cjs
  nala/blocks/ax-columns/ax-columns.test.cjs
  nala/libs/accessibility.cjs
  nala/libs/baseurl.cjs
  nala/libs/customerrors.cjs
  nala/libs/webutil.cjs
  nala/utils/a11y-bot.cjs
  nala/utils/a11y-report.cjs
  nala/utils/base-reporter.cjs
  nala/utils/global.setup.cjs
  nala/utils/nala.cli.cjs
  nala/utils/nala.run.cjs
  nala/utils/pr.run.sh
  nala/utils/slack.cjs
  package-lock.json
  package.json
  playwright.config.cjs
Labels: Ready for Stage, QA Approved

#341 [Design QA] How-To Block
  express/code/blocks/how-to-v2/how-to-v2.css
  express/code/blocks/how-to-v2/how-to-v2.js
Labels: Ready for Stage

#352 [Bug] Long-Form & FAQ Blocks Not Rending Correctly on Staging
  express/code/blocks/faqv2/faqv2.css
  express/code/blocks/faqv2/faqv2.js
Labels: Ready for Stage

#317 [Q1 FY25 | SEO] Marquee Section
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/ax-columns/ax-columns.js
  express/code/blocks/ax-columns/img/ai-image-edit.png
  express/code/blocks/ax-columns/img/cursor-small.svg
  express/code/blocks/ax-columns/img/gen-ai-panel.png
  express/code/blocks/ax-columns/img/marquee-mobile-tablet.png
  express/code/blocks/ax-columns/img/resize-button.png
  express/code/blocks/ax-columns/img/users.png
  test/blocks/ax-columns/ax-columns.test.js
  test/blocks/ax-columns/mocks/marquee.html
Labels: Ready for Stage

#360 [MWPW-172050] How To Carousel States
  express/code/blocks/how-to-steps-carousel/how-to-steps-carousel.css
  express/code/blocks/how-to-steps-carousel/how-to-steps-carousel.js
Labels: Ready for Stage, QA Approved, Ready for QA, accessibility

#395 [MWPW-172373] Text Spacing Share Link V2
  express/code/blocks/template-x/template-rendering.js
  express/code/blocks/template-x/template-x.css
Labels: Ready for Stage, QA Approved, accessibility, run-nala

#409 [MWPW-173725] Hidden or empty element receives focus
  express/code/blocks/fullscreen-marquee/fullscreen-marquee.css
  express/code/blocks/fullscreen-marquee/fullscreen-marquee.js
Labels: Ready for Stage, QA Approved, accessibility

#413 [MWPW-173640] Grid Marquee Additional content not dismissible
  express/code/blocks/grid-marquee/grid-marquee.js
Labels: Ready for Stage, QA Approved, accessibility, run-nala

#421 MWPW-174872: removing card highlight variant
  express/code/blocks/cards/cards.js
Labels: Ready for Stage, QA Approved, accessibility

#393 MWPW-172516: remove : and extra line
  express/code/blocks/template-x/template-rendering.js
Labels: Ready for Stage, QA Approved, accessibility

#388 MWPW-172621: set all svgs to role=presentation
  express/code/scripts/utils.js
Labels: Ready for Stage, QA Approved, accessibility

#382 MWPW-173337: remove Promotion block
  express/code/blocks/promotion/promotion.css
  express/code/blocks/promotion/promotion.js
  express/code/scripts/utils.js
Labels: Ready for Stage, QA Approved, accessibility

#408 [MWPW-172477] Frictionless QA Text Spacing
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
  express/code/icons/dash-rectangle.svg
Labels: bug, Ready for Stage, QA Approved, accessibility

#383 [MWPW-173486] Purpose of link is not clear in context - view all
  express/code/blocks/browse-by-category/browse-by-category.js
  express/code/blocks/template-x/template-x.js
Labels: Ready for Stage, QA Approved, accessibility

#412 MWPW-174662: make a11y video controls bound to .hero-overlay
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
  express/code/scripts/utils/ax-video-controls.js
  express/code/scripts/utils/media.js
  express/code/styles/styles.css
Labels: Ready for Stage, QA Approved, accessibility

#426 [Design QA] How-To Block - FF
  express/code/blocks/how-to-v2/how-to-v2.css
Labels: Ready for Stage

#425 [Design QA] Value Prop Blade
  express/code/blocks/highlight/highlight.css
Labels: Ready for Stage

#420 [Q1 FY25 | SEO] Marquee Section - Fast Follow
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/ax-columns/ax-columns.js
  express/code/blocks/ax-columns/img/marquee-mobile-tablet.png
  express/code/blocks/ax-columns/img/marquee-mobile.png
Labels: Ready for Stage

#417 [MWPW-174996] Update Instrumentation
  express/code/scripts/instrument.js
Labels: Ready for QA, attention needed

#402 Revert "[MWPW-172869][Sev-1] Content Toggle Low Res Fix"
  express/code/blocks/content-toggle/content-toggle.css
  express/code/blocks/content-toggle/content-toggle.js
Labels: bug, Ready for QA, accessibility

#431 MWPW-173192: add dynamic tag based on text content
  express/code/blocks/pricing-cards/pricing-cards.js
Labels: Ready for Stage, accessibility

#430 [MWPW-172044] Pricing Cards Tooltip Update
  express/code/blocks/pricing-cards/pricing-cards.css
  express/code/blocks/pricing-cards/pricing-cards.js
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
  express/code/scripts/widgets/tooltip.css
  express/code/scripts/widgets/tooltip.js
Labels: Ready for Review, Ready for Stage, QA Approved, accessibility

#415 [MWPW-171815] updated share icon wrapper to be sibling instead of child of <a>
  express/code/blocks/template-x/template-rendering.js
  express/code/blocks/template-x/template-x.css
Labels: Ready for Stage, QA Approved, Ready for QA, accessibility

#336 [MWPW-164912] Pricing Cards Discount Voice
  express/code/blocks/pricing-cards/pricing-cards.css
  express/code/blocks/pricing-cards/pricing-cards.js
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
Labels: Ready for Stage, QA Approved, Ready for QA, accessibility

#433 Update frictionless-quick-action.css
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
Labels: Ready for QA, attention needed

#377 MWPW-173964 - AEXG5198 | RTP | (mWeb) Homepage
  express/code/blocks/grid-marquee/grid-marquee.css
  express/code/blocks/grid-marquee/grid-marquee.js
  express/code/blocks/mobile-fork-button/mobile-fork-button.css
  express/code/blocks/mobile-fork-button/mobile-fork-button.js
  test/blocks/grid-marquee/grid-marquee.test.js
  test/blocks/mobile-fork-button/mobile-fork-button.test.js
Labels: Ready for Stage, Ready for QA

#419 [MWPW-166953] Discover-Cards Gallery Style Leakage
  express/code/blocks/discover-cards/discover-cards.css
Labels: Ready for Stage, Ready for QA

#428 [MWPW-175114] FloatingCTA Unhide Same Buttons for Create Blade Blocks
  express/code/blocks/hover-cards/hover-cards.css
  express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.js
  express/code/styles/styles.css
Labels: Ready for Stage, Ready for QA

#435 [Release] Stage to Main
  express/code/blocks/ax-columns/ax-columns.js
  express/code/blocks/discover-cards/discover-cards.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.js
  express/code/blocks/grid-marquee/grid-marquee.css
  express/code/blocks/grid-marquee/grid-marquee.js
  express/code/blocks/hover-cards/hover-cards.css
  express/code/blocks/mobile-fork-button/mobile-fork-button.css
  express/code/blocks/mobile-fork-button/mobile-fork-button.js
  express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.js
  express/code/styles/styles.css
  test/blocks/grid-marquee/grid-marquee.test.js
  test/blocks/mobile-fork-button/mobile-fork-button.test.js
Labels: QA Approved

#439 MWPW-171817-MWPW-172127: Post-release fix play / pause position & heading alignment
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
  express/code/scripts/utils/media.js
  express/code/styles/styles.css
Labels: Ready for Stage, accessibility

#447 Sync Stage with Main
  express/code/blocks/grid-marquee/grid-marquee.css
  express/code/blocks/grid-marquee/grid-marquee.js
  express/code/blocks/mobile-fork-button/mobile-fork-button.css
  express/code/blocks/mobile-fork-button/mobile-fork-button.js
  test/blocks/grid-marquee/grid-marquee.test.js
  test/blocks/mobile-fork-button/mobile-fork-button.test.js
Labels: zero-impact

#434 [MWPW-173410] B2B SUSI-Light
  express/code/blocks/susi-light/susi-light.css
  express/code/blocks/susi-light/susi-light.js
  express/code/scripts/express-delayed.js
  test/blocks/susi-light/mocks/body.html
  test/blocks/susi-light/susi-light.test.js
Labels: QA Approved

#443 [MWPW-174218] Get Started Blade Blocks Stand-alone Ready
  .github/pull_request_template.md
  express/code/blocks/ax-panels/ax-panels.css
  express/code/blocks/ax-panels/ax-panels.js
  express/code/blocks/cta-cards/cta-cards.css
  express/code/blocks/hover-cards/hover-cards.css
  express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.css
Labels: QA Approved

#451 fix mobile dropzone overlap / video
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.css
Labels: Ready for Stage, Ready for QA, accessibility

#380 [MWPW-173481] Fix Columns Height
  express/code/blocks/ax-columns/ax-columns.css
Labels: Ready for Stage, QA Approved

#449 [Bug] Discover More Cards Cut-off - Mobile
  express/code/blocks/discover-cards/discover-cards.css
Labels: Ready for Stage, QA Approved

#437 [Enhancement: Fast Follow] Discover More Cards
  express/code/blocks/discover-cards/discover-cards.css
  express/code/blocks/discover-cards/discover-cards.js
Labels: Ready for Stage, QA Approved

#438 [Enhancement: Fast Follow] Authored Mobile Marquee Image
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/ax-columns/ax-columns.js
Labels: Ready for Stage, QA Approved

#444 [Design QA] Ratings & Reviews Block
  express/code/blocks/quotes/quotes.css
  express/code/scripts/widgets/basic-carousel.css
  express/code/scripts/widgets/basic-carousel.js
Labels: Ready for Stage, QA Approved

#455 MWPW-172127-2: refactor gen-ai card DOM for flex layout
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.js
Labels: Ready for Stage, QA Approved, accessibility
