Repository adobecom/express-milo, pull requests merged in 2025-04, with the labels that each got.

#249 [Accessibility] How-To Block Enhancement
  express/code/blocks/how-to-v2/how-to-v2.js
Labels: Ready for Review

#277 Stage to Main
  express/code/blocks/ax-marquee/ax-marquee.css
  express/code/blocks/content-toggle/content-toggle.js
  express/code/blocks/how-to-v2/how-to-v2.js
Labels: QA Approved

#278 Separate grid marquee ratings
  express/code/blocks/app-ratings/app-ratings.css
  express/code/blocks/app-ratings/app-ratings.js
  test/blocks/app-ratings/app-ratings.test.js
  test/blocks/app-ratings/mocks/body.html
Labels: Ready for Review

#283 Stage to Main
  express/code/blocks/app-ratings/app-ratings.css
  express/code/blocks/app-ratings/app-ratings.js
  express/code/blocks/ax-marquee/ax-marquee.js
  express/code/blocks/template-x/template-x.js
  express/code/scripts/utils/load-carousel.js
  express/code/scripts/widgets/basic-carousel.css
  express/code/scripts/widgets/basic-carousel.js
  test/blocks/app-ratings/app-ratings.test.js
  test/blocks/app-ratings/mocks/body.html
Labels: QA Approved

#282 [Q2 FY25 | UK LP Hero H1 size change
  express/code/blocks/ax-columns/ax-columns.css
Labels: Ready for Stage

#284 [Q2 FY25 | UK LP Gen AI Block Fix
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
Labels: Ready for Stage

#285 [Q2 FY25 | UK LP Replace FAQs
  express/code/blocks/faqv2/faqv2.css
  express/code/icons/minus-heavy.svg
  express/code/icons/plus-heavy.svg
Labels: Ready for Review

#289 Stage to Main
  express/code/blocks/ax-columns/ax-columns.css
  express/code/blocks/faqv2/faqv2.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
  express/code/icons/minus-heavy.svg
  express/code/icons/plus-heavy.svg
Labels: QA Approved

#286 [Accessibility] Grid Marquee App Ratings Accessibility Update
  express/code/blocks/grid-marquee/grid-marquee.js
  test/blocks/grid-marquee/grid-marquee.test.js
Labels: Ready for Review

#295 UI Issues For Gen-AI-Cards Block In Express Homepage
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
Labels: Ready for Review

#280 Print Enhancements
  express/code/blocks/template-x/template-x.css
  express/code/blocks/template-x/template-x.js
  express/code/scripts/template-search-api-v3.js
  express/code/scripts/widgets/masonry.js
Labels: Ready for Review

#297 MWPW-170523: Mobile card adjustment, removed copy link on print
  express/code/blocks/template-x/template-x.css
Labels: Ready for Review

#294 Stage to Main
  express/code/blocks/cta-carousel/cta-carousel.css
  express/code/blocks/cta-carousel/cta-carousel.js
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
  express/code/blocks/grid-marquee/grid-marquee.js
  express/code/blocks/quotes/quotes.css
  express/code/blocks/quotes/quotes.js
  express/code/blocks/ratings/countdown.json
  express/code/blocks/ratings/ratings.css
  express/code/blocks/ratings/ratings.js
  express/code/blocks/template-x/template-x.css
  express/code/blocks/template-x/template-x.js
  express/code/scripts/template-search-api-v3.js
  express/code/scripts/utils/load-carousel.js
  express/code/scripts/utils/ratings-utils.js
  express/code/scripts/widgets/basic-carousel.css
  express/code/scripts/widgets/basic-carousel.js
  express/code/scripts/widgets/grid-carousel.css
  express/code/scripts/widgets/grid-carousel.js
  express/code/scripts/widgets/masonry.js
  express/code/styles/styles.css
  test/blocks/grid-marquee/grid-marquee.test.js
Labels: QA Approved

#299 [MWPW-168206] Update simplified-pricing-cards.js
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
Labels: Ready for Stage, QA Approved

#296 [MWPW-171267] Decorate headline without ctas
  express/code/blocks/grid-marquee/grid-marquee.css
  express/code/blocks/grid-marquee/grid-marquee.js
Labels: Ready for Stage, QA Approved

#291 Allow using Milo columns block on Express pages
  express/code/scripts/utils.js
Labels: Ready for Stage, QA Approved

#303 [MWPW-171491] Add Text block to the FCTA Suppression logic's AllowList
  express/code/styles/styles.css
Labels: Ready for Stage

#304 Stage to main
  express/code/blocks/grid-marquee/grid-marquee.css
  express/code/blocks/grid-marquee/grid-marquee.js
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
  express/code/scripts/utils.js
  express/code/styles/styles.css
Labels: QA Approved

#307 Stage to Main
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
Labels: QA Approved

#302 [MWPW-157412] Added CODEOWNERS
  .github/CODEOWNERS
Labels: Ready for Review

#300 [MWPW-171332] Rm Dependency on old GNAV height
  express/code/blocks/template-list/template-list.css
  express/code/blocks/template-x/template-x.css
  express/code/blocks/template-x/template-x.js
  express/code/styles/styles.css
Labels: Ready for Stage, QA Approved

#309 [MWPW-169109] Browse By Category Opacity Fix
  express/code/blocks/cta-carousel/cta-carousel.css
  express/code/blocks/faqv2/faqv2.css
Labels: Ready for Stage

#305 [MWPW-169110] Comprehensive Gen AI Cards Update
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.js
  express/code/scripts/widgets/compact-nav-carousel.css
  express/code/scripts/widgets/compact-nav-carousel.js
  test/blocks/gen-ai-cards/gen-ai-cards.test.js
  test/blocks/gen-ai-cards/mocks/body.html
  test/scripts/features/compact-nav-carousel/compact-nav-carousel.test.js
  test/scripts/features/compact-nav-carousel/mocks/body.html
  test/scripts/features/compact-nav-carousel/mocks/test.html
Labels: Ready for Stage, QA Approved

#308 Discover Cards Flip [Mobile]: Allow 28px Headline
  express/code/blocks/discover-cards/discover-cards.css
Labels: QA Approved

#312 Stage to Main
  .github/CODEOWNERS
  express/code/blocks/cta-carousel/cta-carousel.css
  express/code/blocks/discover-cards/discover-cards.css
  express/code/blocks/faqv2/faqv2.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.css
  express/code/blocks/gen-ai-cards/gen-ai-cards.js
  express/code/blocks/template-list/template-list.css
  express/code/blocks/template-x/template-x.css
  express/code/blocks/template-x/template-x.js
  express/code/scripts/widgets/compact-nav-carousel.css
  express/code/scripts/widgets/compact-nav-carousel.js
  express/code/styles/styles.css
  test/blocks/gen-ai-cards/gen-ai-cards.test.js
  test/blocks/gen-ai-cards/mocks/body.html
  test/scripts/features/compact-nav-carousel/compact-nav-carousel.test.js
  test/scripts/features/compact-nav-carousel/mocks/body.html
  test/scripts/features/compact-nav-carousel/mocks/test.html
Labels: QA Approved

#316 [MWPW-171648] Tooltip Homepage Fix
  express/code/blocks/pricing-cards/pricing-cards.js
  express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
Labels: Ready for Stage, QA Approved

#318 [MWPW-172485] More Specific Showwith section-metadata for Frictionless Audience
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.css
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
  express/code/scripts/utils.js
  test/scripts/utils.test.js
Labels: Ready for Stage, QA Approved

#315 [MWPW-172159] New Commerce Segmentation Links
  express/code/scripts/utils/pricing.js
  test/scripts/pricing.test.js
Labels: Ready for Review

#313 [MWPW-162405] Remove assigning to innerhtml
  express/code/scripts/utils/template-ckg.js
Labels: Ready for Stage
