Repository adobecom/express-milo, pull requests merged in 2025-08, with the labels that each got.

#492 [NALA][MWPW-176709] Migrate express UI tests from nala repo to Express-Milo repo
  nala/blocks/ax-marquee/ax-marquee.page.js
  nala/blocks/ax-marquee/ax-marquee.spec.js
  nala/blocks/ax-marquee/ax-marquee.test.js
  nala/blocks/cards/cards.page.js
  nala/blocks/cards/cards.spec.js
  nala/blocks/cards/cards.test.js
  nala/blocks/ckg-link-list/ckg-link-list.page.js
  nala/blocks/ckg-link-list/ckg-link-list.spec.js
  nala/blocks/ckg-link-list/ckg-link-list.test.js
  nala/blocks/discover-cards/discover-cards.page.js
  nala/blocks/discover-cards/discover-cards.spec.js
  nala/blocks/discover-cards/discover-cards.test.js
  nala/blocks/gen-ai-cards/gen-ai-cards.page.js
  nala/blocks/gen-ai-cards/gen-ai-cards.spec.js
  nala/blocks/gen-ai-cards/gen-ai-cards.test.js
  nala/blocks/grid-marquee/grid-marquee.page.cjs
  nala/blocks/grid-marquee/grid-marquee.spec.cjs
  nala/blocks/grid-marquee/grid-marquee.test.cjs
  nala/blocks/how-to-steps-carousel/how-to-steps-carousel.page.cjs
  nala/blocks/how-to-steps-carousel/how-to-steps-carousel.spec.cjs
  nala/blocks/how-to-steps-carousel/how-to-steps-carousel.test.cjs
  nala/blocks/image-list/image-list.page.cjs
  nala/blocks/image-list/image-list.spec.cjs
  nala/blocks/image-list/image-list.test.cjs
  nala/blocks/simplified-pricing-cards/simplified-pricing-cards.page.cjs
  nala/blocks/simplified-pricing-cards/simplified-pricing-cards.spec.cjs
  nala/blocks/simplified-pricing-cards/simplified-pricing-cards.test.cjs
  nala/utils/copy-tests.cjs
Labels: QA Approved, run-nala

#496 DEV ENHANCEMENT: Pre-commit Hook For Linting CSS Vars
  .husky/pre-commit
  package.json
  scripts/lint-css-vars.js
Labels: QA Approved, zero-impact

#521 [OPT-33868] More accurate block matching for FloatingCTA rules
  express/code/styles/styles.css
Labels: Ready for Stage, QA Approved, zero-impact

#515 MWPW-174671: Make FAQ block schema optional
  express/code/blocks/faq/faq.js
  test/blocks/faq/faq.test.js
  test/blocks/faq/mocks/body.html
  test/blocks/faq/mocks/hide-faq-schema.html
Labels: Ready for Stage, QA Approved

#533 [HOTFIX] MAX patch
  express/code/blocks/ax-columns/ax-columns.css
Labels: QA Approved

#535 [MWPW-177665][Bug] [Create Page] Template-Carousel Default Index Fix
  express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.js
Labels: bug, Ready for Stage, QA Approved, attention needed

#531 Added cursor rules, updated readme.md
  .cursor/rules/aem-eds-transformation-patterns.mdc
  .cursor/rules/aem-franklin-loading-phases.mdc
  .cursor/rules/aem-markup-sections-blocks.mdc
  .cursor/rules/aem-three-phase-performance.mdc
  .cursor/rules/code-review-standards.mdc
  .cursor/rules/core-web-vitals-standards.mdc
  .cursor/rules/css-render-blocking-diagnosis.mdc
  .cursor/rules/css-variable-linting-standards.mdc
  .cursor/rules/dom-manipulation-best-practices.mdc
  .cursor/rules/dom-structure-preservation.mdc
  .cursor/rules/event-handling-performance.mdc
  .cursor/rules/express-milo-block-patterns.mdc
  .cursor/rules/express-milo-performance-diagnosis.mdc
  .cursor/rules/image-optimization-requirements.mdc
  .cursor/rules/lazy-loading-implementation.mdc
  .cursor/rules/lighthouse-performance-troubleshooting.mdc
  .cursor/rules/nala-test-generation.mdc
  .cursor/rules/resource-loading-strategy.mdc
  .cursor/rules/unit-testing-standards.mdc
  README.md
Labels: QA Approved, zero-impact

#525 Banner - Discover Page Redesign
  express/code/blocks/banner-bg/banner-bg.css
  express/code/blocks/banner-bg/banner-bg.js
  express/code/blocks/banner-bg/img/blue-bg.jpg
  express/code/blocks/banner-bg/img/blue-green-pink-bg.jpg
  express/code/blocks/banner-bg/img/blue-pink-orange-bg.jpg
  express/code/blocks/banner-bg/img/blue-purple-gray-bg.jpg
  express/code/blocks/banner-bg/img/green-blue-red-bg.jpg
  express/code/blocks/banner-bg/img/light-bg.jpg
  express/code/blocks/banner-bg/img/yellow-pink-blue-bg.jpg
  express/code/styles/styles.css
  test/blocks/banner-bg/banner-bg.test.js
  test/blocks/banner-bg/mocks/basic.html
  test/blocks/banner-bg/mocks/light-bg.html
  test/blocks/banner-bg/mocks/multi-button.html
  test/blocks/banner-bg/mocks/phone-number.html
  test/blocks/banner-bg/mocks/with-logo.html
Labels: Ready for Stage, QA Approved

#523 MWPW-176301: How To redesign / grid
  express/code/blocks/how-to-v2/how-to-v2.css
  express/code/blocks/how-to-v3/how-to-v3.css
  express/code/blocks/how-to-v3/how-to-v3.js
  express/code/styles/styles.css
Labels: Ready for Stage, QA Approved

#520 MWPW-176306: Link-List grid and redesign
  express/code/blocks/link-list/link-list.css
  express/code/styles/styles.css
Labels: Ready for Stage, QA Approved

#552 Restore WTR Test Command
  package.json
  test/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.test.js
Labels: QA Approved, attention needed, zero-impact

#551 MWPW-176304: Template Promo for redesign
  express/code/blocks/template-promo/template-promo.css
  express/code/blocks/template-promo/template-promo.js
  express/code/styles/styles.css
Labels: Ready for Review, Ready for Stage, Ready for QA

#536 DOTCOM-163350: Hide floating CTA from accessibility tree near footer
  express/code/scripts/widgets/floating-cta.js
  nala/blocks/floating-button/floating-button.test.cjs
Labels: QA Approved

#561 MWPW-178131: Wayfinder Centered
  express/code/blocks/wayfinder/wayfinder.css
Labels: QA Approved

#566 Update dismissable continue selector.
  express/code/blocks/mobile-fork-button-dismissable/mobile-fork-button-dismissable.js
Labels: QA Approved

#560 Support For Multiple Pricing Tokens In Pricing Cards V2
  express/code/blocks/pricing-cards-v2/pricing-cards-v2.js
Labels: QA Approved, attention needed

#569 Discover - TOC Not Appearing on Safari
  express/code/blocks/toc-seo/toc-seo.js
  test/blocks/toc-seo/toc-seo.test.js
Labels: Ready for Review, QA Approved

#555 [CHORE] Added security key prevention
  .gitignore
Labels: Ready for Stage, zero-impact

#576 [MWPW-178199] TaaS Individual IDs Support
  .gitignore
  express/code/blocks/templates-as-a-service/library/dist/templates-as-a-service.css
  express/code/blocks/templates-as-a-service/library/dist/templates-as-a-service.min.es.js
  express/code/blocks/templates-as-a-service/library/dist/templates-as-a-service.min.es.js.map
  express/code/blocks/templates-as-a-service/library/src/App.css
  express/code/blocks/templates-as-a-service/library/src/components/form/Form.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/template-id-group/TemplateIdGroup.jsx
  express/code/blocks/templates-as-a-service/library/src/components/form/topics/TopicsGroups.jsx
  express/code/blocks/templates-as-a-service/library/src/components/results/QueryResults.jsx
  express/code/blocks/templates-as-a-service/library/src/components/results/Template.jsx
  express/code/blocks/templates-as-a-service/library/src/utils/form-hooks.js
  express/code/blocks/templates-as-a-service/library/src/utils/recipe-form-utils.js
  express/code/blocks/templates-as-a-service/library/src/utils/useData.js
  express/code/scripts/template-utils.js
  express/code/styles/styles.css
  test/scripts/template-utils.test.js
Labels: Ready for Stage, zero-impact
