Repository adobecom/express-milo, pull requests merged in 2025-10, with the labels that each got.

#619 [MWPW-181029] Enable frictionless QAs on safari browser
  express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
  express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
  express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.js
  express/code/scripts/utils.js
  express/code/scripts/utils/frictionless-utils.js
  test/scripts/utils.test.js
Labels: QA Approved, run-nala

#628 MWPW-178663: Template filter search / filter show on pageload
  express/code/blocks/grid-marquee/grid-marquee.css
  nala/blocks/search-marquee/search-marquee.page.cjs
  nala/blocks/search-marquee/search-marquee.spec.cjs
  nala/blocks/search-marquee/search-marquee.test.cjs
  nala/blocks/template-x/template-x.test.cjs
  test/blocks/search-marquee/mocks/body.html
  test/blocks/template-x/template-x.test.js
Labels: run-nala

#658 Sync Stage with Main
  express/code/styles/styles.css
Labels: Ready for Review, QA Approved

#645 MWPW-181326: Enhance how-to-v2 unit tests and remove min-width constraints
  express/code/blocks/how-to-v2/how-to-v2.css
  nala/blocks/how-to-v2/how-to-v2.page.cjs
  nala/blocks/how-to-v2/how-to-v2.spec.cjs
  nala/blocks/how-to-v2/how-to-v2.test.cjs
Labels: QA Approved

#589 How to cards schema
  express/code/blocks/how-to-cards/how-to-cards.css
  express/code/blocks/how-to-cards/how-to-cards.js
Labels: do not merge, QA Approved

#639 Implement Replacement for Reviews API
  express/code/blocks/quotes/quotes.js
  express/code/blocks/ratings/ratings.js
  express/code/scripts/utils/ratings-utils.js
Labels: do not merge, QA Approved

#673 Nala test automation for banner block.
  nala/blocks/banner/banner.page.cjs
  nala/blocks/banner/banner.spec.cjs
  nala/blocks/banner/banner.test.cjs
Labels: Ready for Review, Ready for Stage, zero-impact

#651 MWPW-175184: Fix content-toggle-v2 card height calculation by using visibility-based hiding
  express/code/blocks/content-toggle-v2/content-toggle-v2.css
  express/code/blocks/content-toggle-v2/content-toggle-v2.js
  nala/blocks/content-toggle-v2/content-toggle-v2.test.cjs
Labels: QA Approved, attention needed
